name: Trigger Webhook via POST

on:
  push:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST to webhook
        run: |
          curl -X POST http://178.33.40.53:5678/webhook-test/product-check \
          -H "Content-Type: application/json" \
          -d '{"trigger": "GitHub Action Deploy"}'
