name: Trigger Webhook

on:
  push:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger POST request to webhook
        run: |
          curl -X POST http://178.33.40.53:5678/webhook-test/product-check \
            -H "Content-Type: application/json" \
            -d '{"message": "Triggered from GitHub Action"}'
