name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy HTML via curl
        run: |
          curl -X POST http://178.33.40.53:5678/webhook-test/product-check \
          -H "Content-Type: text/html" \
          --data-binary @index.html
